server:
  port: 8087

spring:
  application:
    name: user-profile-service
  
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  
  cache:
    type: simple
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-namata.us.auth0.com/

logging:
  level:
    com.namata.userprofile: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG