server:
  port: 8086
  address: 0.0.0.0

spring:
  application:
    name: user-profile-service
  profiles:
    active: dev
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:namata_profile}
    username: ${DB_USERNAME:postgres} 
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      maximum-pool-size: 10
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        connection:
          autocommit: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  # Redis temporariamente desabilitado para teste
  # redis:
  #   host: ${REDIS_HOST:localhost}
  #   port: ${REDIS_PORT:6379}
  #   password: ${REDIS_PASSWORD:}
  #   database: 0
  #   timeout: 2000ms
  #   lettuce:
  #     pool:
  #       max-active: 8
  #       max-idle: 8
  #       min-idle: 0
  
  # cache:
  #   type: redis
  #   redis:
  #     time-to-live: 1800000 # 30 minutos
  
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true

app:
  auth:
    jwt:
      secret: ${JWT_SECRET:10a4fbca7931c103edca921d87fa434fbd45f944e1c2ffc05d96408283201e60}
  services:
    auth-service:
      url: ${AUTH_SERVICE_URL:http://auth-service:8082}
    trail-service:
      url: ${TRAIL_SERVICE_URL:http://trail-service:8085}
  upload:
    profile-pictures:
      directory: ${PROFILE_PICTURES_UPLOAD_DIR:/app/uploads/profile-pictures}

logging:
  level:
    com.namata.userprofile: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html