server:
  port: 8082
  address: 0.0.0.0

spring:
  application:
    name: user-profile-service
  
  security:
    enabled: false
  
  datasource:
    url: jdbc:postgresql://localhost:5432/namata_profile
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      connection-timeout: 20000
      maximum-pool-size: 10
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        connection:
          autocommit: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  # redis:
  #   host: ${REDIS_HOST:localhost}
  #   port: ${REDIS_PORT:6379}
  #   password: ${REDIS_PASSWORD:}
  #   timeout: 2000ms
  
  flyway:
    enabled: false

jwt:
  secret: ${JWT_SECRET:NaMataSecretKeyForJWTTokenGenerationAndValidation2024}

auth-service:
  url: ${AUTH_SERVICE_URL:http://192.168.1.9:8080}

logging:
  level:
    com.namata.userprofile: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html